"""user_id_must_be_not_unique

Revision ID: 423aff5d1252
Revises: 4e124c3138cb
Create Date: 2025-08-30 00:04:01.952932

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '423aff5d1252'
down_revision: Union[str, Sequence[str], None] = '4e124c3138cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('answers_user_id_key'), 'answers', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('answers_user_id_key'), 'answers', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
