"""add_ondelete

Revision ID: ed2429092ffd
Revises: 65e4ee4e2b01
Create Date: 2025-08-28 15:14:51.626490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed2429092ffd'
down_revision: Union[str, Sequence[str], None] = '65e4ee4e2b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('answer_question_id_fkey'), 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key(op.f('answer_question_id_fkey'), 'answer', 'question', ['question_id'], ['id'])
    # ### end Alembic commands ###
